spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcDataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/banco
    username: root
    password: seña_Señalada32
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080